@extends('layouts.app')

@section('content')
    <div class="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm font-semibold uppercase text-osca-primary">Records</p><h1 class="text-3xl font-bold">Senior citizen masterlist</h1></div><a class="rounded bg-osca-primary px-4 py-2 text-white" href="{{ route('senior-citizens.create') }}">Register senior citizen</a></div>
    <div class="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach ($counts as $label => $count)<div class="rounded-lg border bg-white p-4"><p class="text-sm text-slate-600">{{ $label }}</p><p class="text-2xl font-bold">{{ number_format($count) }}</p></div>@endforeach</div>
    <form method="GET" class="mb-5 grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-5"><label class="text-sm">Search <input name="search" value="{{ request('search') }}" placeholder="OSCA ID or name" class="mt-1 w-full rounded border p-2"></label><label class="text-sm">Barangay <select name="barangay_id" class="mt-1 w-full rounded border p-2"><option value="">All barangays</option>@foreach ($barangays as $barangay)<option value="{{ $barangay->id }}" @selected(request('barangay_id') == $barangay->id)>{{ $barangay->name }}</option>@endforeach</select></label><label class="text-sm">Age <select name="age" class="mt-1 w-full rounded border p-2"><option value="">All ages</option>@foreach (['60-69', '70-79', '80+'] as $age)<option value="{{ $age }}" @selected(request('age') === $age)>{{ $age }}</option>@endforeach</select></label><label class="text-sm">Status <select name="status" class="mt-1 w-full rounded border p-2"><option value="">All statuses</option>@foreach (\App\Enums\SeniorCitizenStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ ucfirst(strtolower($status->value)) }}</option>@endforeach</select></label><div class="flex items-end gap-2"><button class="rounded bg-osca-primary px-4 py-2 text-white">Filter</button><a href="{{ route('senior-citizens.index') }}" class="px-2 py-2 underline">Reset</a></div></form>
    <p class="mb-2 text-sm text-slate-600">{{ $seniorCitizens->total() }} results</p>
    <div class="overflow-x-auto rounded-lg border bg-white"><table class="w-full min-w-160 text-left text-sm"><thead class="bg-slate-100"><tr>@foreach (['OSCA ID', 'Last name', 'First name', 'Middle name', 'Age', 'Barangay', 'Status', ''] as $heading)<th scope="col" class="p-3">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y">@forelse ($seniorCitizens as $seniorCitizen)<tr><td class="p-3">{{ $seniorCitizen->osca_id_number ?: '—' }}</td><td class="p-3">{{ $seniorCitizen->last_name }}</td><td class="p-3">{{ $seniorCitizen->first_name }}</td><td class="p-3">{{ $seniorCitizen->middle_name ?: '—' }}</td><td class="p-3">{{ $seniorCitizen->birth_date->age }}</td><td class="p-3">{{ $seniorCitizen->barangay->name }}</td><td class="p-3"><x-badge :status="$seniorCitizen->status" /></td><td class="p-3"><a class="text-osca-primary underline" href="{{ route('senior-citizens.show', $seniorCitizen) }}" aria-label="View {{ $seniorCitizen->full_name }}">View</a></td></tr>@empty<tr><td colspan="8" class="p-6 text-center text-slate-600">No senior citizen records match these filters.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-4">{{ $seniorCitizens->links() }}</div>
@endsection
